#datanodei Placed by confd. Do not hand edit.

cluster.name: es
network.host: _site_
node.data: false
node.master: true
node.name: ${HOSTNAME}

bootstrap.mlockall: true
discovery.zen.ping.multicast.enabled: false


discovery.zen.ping.unicast.hosts: ["masters.elasticsearch"]

